name: Backporting
author: Thibault Derousseaux <tibdex@gmail.com>
description: Automatically backport PRs to other branches by simply labeling them.
inputs:
  add_labels:
    description: Comma separated list of labels to add to the backport PR.
    required: false
  github_token:
    description: Token for the GitHub API.
    required: true
  title_template:
    description: Template for the title of the backport PR.
    required: false
    default: "[Backport {{base}}] {{originalTitle}}"
  issue_labels:
    description: Comma separated list of labels to add to the issue that will be
      created if the backport fails. If empty then no issue will be
      created.
    required: false

runs:
  using: node12
  main: dist/index.js
branding:
  icon: arrow-left-circle
  color: purple
